version: 2.1
jobs:
  plone-43:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Tests setup
          command: |
            sudo pip install virtualenv==16.7.8
            virtualenv ci_tests
            ci_tests/bin/pip install -r requirements.txt
            ci_tests/bin/buildout -c buildout-4.3.cfg
      - run:
          name: Run tests
          command: |
            bin/test
  plone-51:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Tests setup
          command: |
            sudo pip install virtualenv==16.7.8
            virtualenv ci_tests
            ci_tests/bin/pip install -r requirements.txt
            ci_tests/bin/buildout -c buildout-5.1.cfg
      - run:
          name: Run tests
          command: |
            bin/test
workflows:
 version: 2
 plone-43:
   jobs:
     - plone-43
 plone-51:
   jobs:
     - plone-51
