name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        plone-version: [4.3, 5.1]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: Setup for tests
      run: |
        pip install -r requirements.txt
        buildout -c buildout-${{matrix.plone-version}}.cfg
    - name: Run tests
      run: |
        bin/test
